// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Net60_ApiTemplate_20231.Models
{
    [Table("HospitalMoph")]
    public partial class HospitalMoph
    {
        [Key]
        public int HospitalId { get; set; }
        public int? HospitalOriginId { get; set; }
        [StringLength(255)]
        public string HospitalName { get; set; }
        [StringLength(9)]
        public string HospitalNineCode { get; set; }
        [StringLength(5)]
        public string HospitalFiveCode { get; set; }
        [StringLength(20)]
        public string HospitalLicence { get; set; }
        [StringLength(150)]
        public string HospitalTypeName { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(150)]
        public string No { get; set; }
        [StringLength(150)]
        public string Moo { get; set; }
        [StringLength(150)]
        public string Room { get; set; }
        [StringLength(150)]
        public string Floor { get; set; }
        [StringLength(255)]
        public string BuildingName { get; set; }
        [StringLength(150)]
        public string VillageName { get; set; }
        [StringLength(150)]
        public string Soi { get; set; }
        [StringLength(150)]
        public string Road { get; set; }
        [StringLength(255)]
        public string AddressDetail { get; set; }
        public int? SubdistrictId { get; set; }
        [StringLength(150)]
        public string SubdistrictName { get; set; }
        public int? DistrictId { get; set; }
        [StringLength(150)]
        public string DistrictName { get; set; }
        public int? ProvinceId { get; set; }
        [StringLength(150)]
        public string ProvinceName { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? UpdateOrigin { get; set; }
    }
}