// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Net60_ApiTemplate_20231.Models
{
    [Table("ProductGroup")]
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public Guid ProductGrouptId { get; set; }
        [Required]
        [StringLength(255)]
        public string ProductGroupName { get; set; }
        public int CreatedByUserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime UpdatedDate { get; set; }
        public bool isActive { get; set; }

        [InverseProperty("ProductGroup")]
        public virtual ICollection<Product> Products { get; set; }
    }
}